import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import { PrismaClient } from "./generated/prisma";
import { cookies } from 'next/headers';
import { createServerClient } from '@supabase/ssr';

const prisma = new PrismaClient();

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

  const cookieStore = cookies();

  const supabase = createServerClient(
    supabaseUrl,
    supabaseAnonKey,
    {
      cookies: {
        getAll() {
          return cookieStore.getAll();
        },
        setAll(cookiesToSet) {
          cookiesToSet.forEach(({ name, value, options }) => {
            cookieStore.set(name, value, options);
          });
        },
      },
    }
  );

  const { data: { user: currentUser } } = await supabase.auth.getUser();

  let pendingInvitations = [];
  if (currentUser) {
    pendingInvitations = await prisma.groupMember.findMany({
      where: {
        userId: currentUser.id,
        hasAcceptedInvite: false,
      },
      include: {
        group: {
          select: {
            id: true,
            name: true,
            createdBy: {
              select: {
                displayName: true,
                email: true,
              },
            },
          },
        },
      },
    });
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header currentUser={currentUser} pendingInvitations={pendingInvitations} />
        <main>{children}</main>
      </body>
    </html>
  );
}
